import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';

// Run against a production preview or the deployed URL via PAGES_URL.
test('Pages subpath supports navigation, query filters, exam recovery and persisted results', async ({ page }, testInfo) => {
  const errors: string[] = [];
  const badResponses: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  page.on('response', response => { if (response.status() >= 400) badResponses.push(`${response.status()} ${response.url()}`); });
  const base = testInfo.project.use.baseURL!;
  await page.setViewportSize({ width: 820, height: 1180 });
  expect((await page.goto(base))!.status()).toBe(200);
  await expect(page.getByRole('heading', { name: /오늘의 훈련/ })).toBeVisible();
  await page.getByRole('link', { name: '집중 훈련', exact: true }).click();
  await expect(page).toHaveURL(`${base}#/training`);
  await expect(page.getByRole('heading', { name: '오늘은 어떻게 훈련할까요?' })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('radio', { name: /REAL EXAM — 90 MIN/ })).toBeVisible();
  await page.getByRole('link', { name: '문제 은행', exact: true }).click();
  await page.reload();
  await expect(page.getByRole('heading', { name: '문제 은행', exact: true })).toBeVisible();
  await page.goBack();
  await expect(page.getByRole('radio', { name: /REAL EXAM — 90 MIN/ })).toBeVisible();
  await page.goForward();
  await expect(page.getByRole('heading', { name: '문제 은행', exact: true })).toBeVisible();
  await page.goto(`${base}#/training?domain=Genetics`);
  await expect(page.getByRole('combobox', { name: '영역', exact: true })).toHaveValue('Genetics');
  await page.goto(`${base}#/training?review=1`);
  await expect(page.getByRole('heading', { name: '우선순위 복습', exact: true })).toBeVisible();
  await page.goto(`${base}#/training`);
  await page.getByRole('link', { name: '본문으로 건너뛰기' }).focus();
  await page.keyboard.press('Enter');
  await expect(page).toHaveURL(`${base}#/training`);
  await expect(page.locator('main')).toBeFocused();
  await page.getByRole('radio', { name: /REAL EXAM — 90 MIN/ }).check();
  await expect(page.getByRole('button', { name: 'REAL EXAM 시작' })).toBeDisabled();
  await page.getByLabel('DRAFT 개발용 문제 포함').check();
  await page.getByRole('button', { name: 'REAL EXAM 시작' }).click();
  await expect(page.getByRole('timer')).toContainText(/(90:00|89:\d{2})/);
  await page.locator('[data-choice]').nth(1).click();
  await expect(page.locator('[data-choice]').nth(1)).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: '2번 미방문', exact: true }).click();
  await page.keyboard.press('l');
  await expect(page.getByRole('button', { name: '2번 Later', exact: true })).toBeVisible();
  await page.keyboard.press('s');
  await expect(page.getByRole('button', { name: '3번 Skip', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '1번 답변함', exact: true }).click();
  await page.reload();
  await expect(page.locator('[data-choice]').nth(1)).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByRole('button', { name: '2번 Later', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: '3번 Skip', exact: true })).toBeVisible();
  await expect(page.locator('.choice.correct,.choice.wrong,.feedback,.explanation')).toHaveCount(0);
  await expect(page.getByText(/정답입니다|오답입니다|정답과 해설|SCORE LEAK|MISCONCEPTION|확신도/)).toHaveCount(0);
  await expect(page.getByRole('navigation', { name: '주 메뉴' })).toHaveCount(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await expect(page.getByRole('timer')).toBeInViewport();
  await expect(page.getByRole('button', { name: '27번 미방문', exact: true })).toBeInViewport();
  await page.screenshot({ path: testInfo.outputPath('pages-tablet-exam.png'), fullPage: true });
  await page.getByRole('button', { name: '시험 제출', exact: true }).click();
  await page.getByRole('button', { name: '제출하고 결과 보기' }).click();
  await expect(page.getByRole('heading', { name: 'REAL EXAM 결과', exact: true })).toBeVisible();
  expect(page.url()).toContain(`${base}#/session/`);
  await page.reload();
  await expect(page.getByTestId('exam-stat-total')).toContainText('27');
  await expect(page.getByTestId('exam-stat-attempted')).toContainText('1');
  await page.screenshot({ path: testInfo.outputPath('pages-tablet-report.png'), fullPage: true });
  expect(errors).toEqual([]);
  expect(badResponses).toEqual([]);
});

test('Pages preserves Training history and JSON transfer in fresh browser storage', async ({ page, browser }, testInfo) => {
  const base = testInfo.project.use.baseURL!;
  await page.goto(`${base}#/training`);
  await page.getByLabel('DRAFT 개발용 문제 포함').check();
  await page.getByLabel('문항 수', { exact: true }).fill('1');
  await page.getByRole('button', { name: '훈련 시작', exact: true }).click();
  await page.keyboard.press('1');
  await page.keyboard.press('Enter');
  await page.getByRole('button', { name: '확신도 3', exact: true }).click();
  await page.getByRole('button', { name: '결과 보기', exact: true }).click();
  await expect(page.getByRole('heading', { name: '훈련 결과', exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByTestId('stat-attempted')).toContainText('1');
  await page.getByRole('link', { name: '대시보드', exact: true }).click();
  const downloadEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export Study Data' }).click();
  const exported = JSON.parse(await readFile((await (await downloadEvent).path())!, 'utf8'));
  expect(exported.questions).toHaveLength(27);
  expect(exported.questions.every((q: { sourceType: string }) => q.sourceType === 'DRAFT')).toBe(true);
  expect(exported.sessions).toHaveLength(1);
  const clean = await browser.newContext();
  try {
    const fresh = await clean.newPage();
    await fresh.goto(base);
    await fresh.getByLabel('학습 데이터 JSON 파일', { exact: true }).setInputFiles({ name: 'pages-transfer.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(exported)) });
    await fresh.getByRole('button', { name: '가져오기 적용' }).click();
    await expect(fresh.getByTestId('history')).toContainText('1문항');
    await fresh.reload();
    await fresh.getByTestId('history').getByRole('link').click();
    await expect(fresh.getByTestId('stat-attempted')).toContainText('1');
    await fresh.getByRole('link', { name: '문제 은행', exact: true }).click();
    // Clone an existing DRAFT only inside this isolated test profile.
    const question = { ...exported.questions[0], id: 'pages-import-fixture' };
    await fresh.getByLabel('문제 JSON 파일', { exact: true }).setInputFiles({ name: 'pages-question.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify([question])) });
    await fresh.getByRole('button', { name: '가져오기 적용' }).click();
    await expect(fresh.getByRole('status')).toContainText('문제 1개');
    await fresh.reload();
    await fresh.getByLabel('문제 검색').fill('pages-import-fixture');
    await expect(fresh.locator('summary').filter({ hasText: question.question })).toBeVisible();
  } finally { await clean.close(); }
});
