import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { emptyData } from '../src/model';
import { seedQuestions } from '../src/seed';
import { act, createSession } from '../src/sessionEngine';
import { fixture } from './fixtures/qf';
import { validateQFPackage } from '../src/qfImport';

test.use({ viewport: { width: 820, height: 1180 }, hasTouch: true, trace: 'off', screenshot: 'off', video: 'off' });
test('합성 QF import → 네 형식 풀이 → 복구 → 제출/자기 채점 → 백업 복원', async ({ page, browser }) => {
  const p = validateQFPackage(fixture());
  const file = { name: 'synthetic-qf.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(p)) };
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  const mutations: string[] = [];
  page.on('request', req => { if (!['GET', 'HEAD'].includes(req.method())) mutations.push(req.method()); });
  let legacy = createSession({ ...emptyData(), questions: seedQuestions }, { mode: 'RECALL', count: 1, timeLimitSec: 60, includeDrafts: true }, 1000, 'legacy-before-qf');
  legacy = act(legacy, 'legacy-before-qf', { type: 'submit', answer: 0 }, 2000);
  legacy = act(legacy, 'legacy-before-qf', { type: 'finish' }, 3000);
  await page.clock.install({ time: new Date('2026-10-08T00:00:00Z') });
  await page.goto('/');
  await page.getByLabel('학습 데이터 JSON 파일').setInputFiles({ name: 'legacy.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(legacy)) });
  await page.getByRole('button', { name: '가져오기 적용' }).click();
  await expect(page.getByRole('status')).toContainText('가져오기 완료');
  await page.goto('/question-factory');
  await page.getByLabel('QF JSON 파일').setInputFiles(file);
  await expect(page.locator('.import-preview')).toContainText('MCQ 9');
  await expect(page.locator('.import-preview')).toContainText('예상 시간 30분');
  await expect(page.locator('.import-preview')).toContainText('CONSTRUCTED_RESPONSE 1');
  await page.getByRole('button', { name: '가져오기 적용' }).click();
  await expect(page.getByRole('status')).toContainText('QF 세트 1개');
  await page.getByLabel('QF JSON 파일').setInputFiles(file);
  await expect(page.locator('.import-preview')).toContainText('QF 세트 0개');
  await page.getByRole('button', { name: '가져오기 적용' }).click();
  await page.getByRole('button', { name: 'DAILY-15 시작 · 30분' }).click();
  await expect(page.getByRole('timer')).toContainText('30:00');
  await expect(page.locator('.feedback,.explanation,.qf-english')).toHaveCount(0);
  await page.locator('[data-choice]').nth(Object.keys(p.questions[0].question.options!).indexOf(p.questions[0].question.correct_answer!)).click();
  await page.getByRole('button', { name: 'Later · 나중에', exact: true }).click();
  await expect(page.getByRole('button', { name: '1번 문항', exact: true })).toContainText('L');
  const combination = p.questions.findIndex(w => w.question.format === 'COMBINATION');
  await page.getByRole('button', { name: (combination + 1) + '번 문항', exact: true }).click();
  await expect(page.locator('.qf-statements dt')).toHaveText(['ㄱ','ㄴ','ㄷ']);
  await page.locator('[data-choice]').nth(Object.keys(p.questions[combination].question.options!).indexOf(p.questions[combination].question.correct_answer!)).click();
  await page.getByRole('button', { name: 'Skip · 건너뛰기', exact: true }).click();
  await expect(page.getByRole('button', { name: (combination + 1) + '번 문항', exact: true })).toContainText('S');
  const short = p.questions.findIndex(w => w.question.format === 'SHORT');
  await page.getByRole('button', { name: (short + 1) + '번 문항', exact: true }).click();
  await page.getByLabel('단답형 답안', { exact: true }).fill('  첫 답안  ');
  await expect(page.getByRole('status')).toContainText('답안 저장됨');
  await page.getByLabel('단답형 답안', { exact: true }).fill('  수정한 단답 원문  ');
  await page.getByRole('button', { name: '확신도 4', exact: true }).click();
  const cr = p.questions.findIndex(w => w.question.format === 'CONSTRUCTED_RESPONSE');
  await page.getByRole('button', { name: (cr + 1) + '번 문항', exact: true }).click();
  const answer = 'First line.\n수정 전 두 번째 줄';
  await page.getByLabel('서술형 답안', { exact: true }).fill(answer);
  await page.setViewportSize({ width: 820, height: 640 });
  const previous = await page.getByRole('button', { name: '이전 문항', exact: true }).boundingBox();
  expect(previous && previous.y >= 0 && previous.y + previous.height < 640).toBe(true);
  await page.setViewportSize({ width: 820, height: 1180 });
  await page.getByLabel('서술형 답안', { exact: true }).pressSequentially(' → 수정한 답안', { delay: 5 });
  await expect(page.getByRole('status')).toContainText('답안 저장됨');
  await page.clock.fastForward(65000);
  await page.reload();
  await expect(page.getByLabel('서술형 답안', { exact: true })).toHaveValue(answer + ' → 수정한 답안');
  await expect(page.locator('.feedback,.explanation,.qf-english')).toHaveCount(0);
  await expect(page.getByRole('timer')).not.toContainText('30:00');
  await page.getByRole('button', { name: '1번 문항', exact: true }).click();
  await expect(page.locator('[data-choice][aria-pressed="true"]')).toHaveCount(1);
  await page.getByRole('button', { name: '세트 제출', exact: true }).click();
  await page.getByRole('button', { name: '세트 제출하고 결과 보기' }).click();
  await expect(page.getByRole('heading', { name: 'DAILY-15 결과', exact: true })).toBeVisible();
  await page.getByRole('button', { name: (cr + 1) + '번 · 미채점', exact: true }).click();
  await expect(page.getByRole('region', { name: '원본 채점 기준' })).toContainText(p.questions[cr].question.scoring_points![0].point);
  await expect(page.getByRole('heading', { name: 'Stage 3 English Review' })).toBeVisible();
  await page.getByLabel('채점 기준 1 충족 여부', { exact: true }).selectOption('true');
  await expect(page.getByLabel('채점 기준 1 충족 여부', { exact: true })).toBeEnabled();
  await page.getByRole('button', { name: '부분 정답', exact: true }).click();
  await page.getByRole('combobox', { name: '실패 유형', exact: true }).selectOption('L');
  await expect(page.getByRole('combobox', { name: '실패 유형', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: (short + 1) + '번 · 미채점', exact: true }).click();
  await expect(page.locator('pre').first()).toHaveText('수정한 단답 원문');
  await page.getByRole('button', { name: '정답', exact: true }).click();
  await page.goto('/');
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export Study Data' }).click();
  const download = await downloadPromise;
  const exported = JSON.parse(await readFile((await download.path())!, 'utf8'));
  expect(exported.qfPackages).toEqual([p]);
  expect(exported.questions).toEqual(seedQuestions);
  expect(exported.sessions).toEqual(legacy.sessions);
  expect(exported.responses).toEqual(legacy.responses);
  expect(exported.qfSessions).toHaveLength(1);
  expect(exported.qfResponses[cr].selfGrade).toBe('PARTIAL');
  expect(exported.qfResponses[cr].rubricChecks).toEqual([true]);
  expect(exported.qfResponses[0].triage).toBe('LATER');
  expect(exported.qfResponses[combination].triage).toBe('SKIP');
  expect(exported.qfResponses[cr].correct).toBeNull();
  expect(exported.qfResponses[cr].failureType).toBe('L');
  expect(exported.qfResponses[short].textAnswer).toBe('  수정한 단답 원문  ');
  expect(exported.qfResponses[short].confidence).toBe(4);
  expect(exported.qfResponses[0].revisited).toBe(true);
  expect(exported.qfResponses[cr].answerChangeCount).toBeGreaterThan(0);
  const restored = await browser.newContext({ viewport: { width: 820, height: 1180 } });
  const second = await restored.newPage();
  await second.goto(new URL('/', page.url()).href);
  await second.getByLabel('학습 데이터 JSON 파일').setInputFiles({ name: 'study-backup.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(exported)) });
  await second.getByRole('button', { name: '가져오기 적용' }).click();
  await expect(second.getByRole('status')).toContainText('QF 풀이 1회');
  await second.goto(new URL('/qf-session/' + exported.qfSessions[0].id, page.url()).href);
  await expect(second.getByTestId('qf-stats')).toContainText('부분 정답 1');
  await second.getByRole('button', { name: (cr + 1) + '번 · 부분 정답', exact: true }).click();
  await expect(second.getByLabel('채점 기준 1 충족 여부', { exact: true })).toHaveValue('true');
  await second.goto(new URL('/question-factory', page.url()).href);
  await second.getByRole('button', { name: 'DAILY-15 시작 · 30분' }).click();
  await second.clock.install();
  await second.clock.fastForward(1800001);
  await expect(second.getByRole('heading', { name: 'DAILY-15 결과', exact: true })).toBeVisible();
  await expect(second.getByTestId('qf-stats')).toContainText('미응답 15');
  await restored.close();
  expect(errors).toEqual([]);
  expect(mutations).toEqual([]);
});
