import { useState } from 'react';
import { FAILURES, TAXONOMY, type FailureType, type Response, type Session, type StudyData } from './model';
import { EXAM_FLAG_LABELS, examFlags, examMetadataStats, examReport, type ExamFlag } from './examMetrics';
import { reflectExam } from './sessionEngine';
import { Link, percent, type Save } from './ui';

// Display whole seconds: recorded wall-clock visits are practical estimates of attention.
const timeText = (ms: number) => { const seconds = Math.round(ms / 1000); return `${Math.floor(seconds / 60)}분 ${seconds % 60}초`; };

export function ExamReport({ data, session, onSave, busy }: { data: StudyData; session: Session; onSave: Save; busy: boolean }) {
  const [reviewId, setReviewId] = useState<string | null>(null);
  const [by, setBy] = useState<'language' | 'stimulusType' | 'contextNovelty'>('language');
  const report = examReport(data, session);
  if (!report) return null;
  const rows = session.questionIds.map(id => data.responses.find(r => r.sessionId === session.id && r.questionId === id)!);
  const groups = examMetadataStats(data, session, by);
  const review = rows.find(r => r.questionId === reviewId);
  const reviewQuestion = data.questions.find(q => q.id === reviewId);
  const hasDrafts = data.questions.some(q => session.questionIds.includes(q.id) && q.sourceType === 'DRAFT');
  const metrics = [ ['total', '전체 문항', report.total], ['attempted', '시도', report.attempted], ['correct', '정답', report.correct], ['incorrect', '오답', report.incorrect], ['unanswered', '미응답', report.unanswered], ['accuracy', '정확도 · 정답/시도', report.attempted ? percent(report.accuracy) : '—'], ['attemptRate', '시도율', percent(report.attemptRate)], ['median', '응답 시간 중앙값', report.attempted ? timeText(report.medianMs) : '—'] ] as const;
  function openReview(id: string) { setReviewId(id); setTimeout(() => document.getElementById('exam-review')?.scrollIntoView({ block: 'start' }), 0); }
  return <>
    <header className="page-heading"><div><span className="eyebrow">REAL EXAM DEBRIEF</span><h1>REAL EXAM 결과</h1><p>{session.endReason === 'EXPIRED' ? '시간 만료 · 자동 제출' : '직접 제출'} · {timeText(session.endedAt! - session.startedAt)} / {session.timeLimitSec / 60}분</p></div><Link className="button primary" href="/training">다시 훈련하기 →</Link></header>
    {hasDrafts && <p className="exam-draft"><strong>DRAFT · 개발용 시험 결과</strong> — 미검증 fixture의 결과이며 실제 시험 성적을 예측하지 않습니다.</p>}
    <section className="stats" aria-label="시험 요약">{metrics.map(([key, label, value]) => <div className="stat" data-testid={`exam-stat-${key}`} key={key}><span className="stat-label">{label}</span><strong>{value}</strong></div>)}</section>
    <section className="panel"><div className="section-heading"><h2>SCORE LEAK</h2><span className="small muted">훈련용 휴리스틱 · 중복 집계 가능</span></div><dl className="score-leak">{(Object.keys(EXAM_FLAG_LABELS) as ExamFlag[]).map(f => <div key={f}><dt>{EXAM_FLAG_LABELS[f]}</dt><dd data-testid={`leak-${f}`}>{report.flags[f]}</dd></div>)}</dl><p className="panel-note">Known-but-lost는 실행 과정에서 놓쳤을 가능성이 있는 미응답 후보입니다. 실제 지식 보유나 회복 가능한 점수를 확정하지 않습니다.</p></section>
    <div className="two-column"><section className="panel"><h2>시간 배분</h2><dl className="time-breakdown">{[['정답 문항', report.correctTimeMs], ['오답 문항', report.incorrectTimeMs], ['미응답 문항', report.unansweredTimeMs], ['Later를 사용한 문항', report.laterTimeMs], ['Skip을 사용한 문항', report.skippedTimeMs], ['재방문한 문항', report.revisitedTimeMs]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{timeText(value as number)}</dd></div>)}</dl><p className="panel-note">문항을 열어 둔 전체 시간의 합계입니다. Later / Skip / 재방문 집계는 해당 문항의 모든 방문 시간을 포함하며 서로 겹칩니다. 탭 비활성·새로고침 시간도 포함합니다.</p></section>
      <section className="panel"><h2>BAD INVESTMENTS</h2><p className="small muted">정답을 얻지 못한 문항 · 투자 시간 순</p>{report.worst.length ? <ol className="rank-list">{report.worst.slice(0, 5).map((r, i) => { const q = data.questions.find(q => q.id === r.questionId)!; return <li key={r.id}><span className="rank">{i + 1}</span><div><button className="text-button investment-link" onClick={() => openReview(q.id)}>{TAXONOMY[q.domain]} · {q.subdomain}</button><p>{r.correct === false ? '오답' : '미응답'}{examFlags(data, session, r).includes('BAD_INVESTMENT') ? ' · BAD_INVESTMENT' : ''}</p></div><span>{timeText(r.responseTimeMs)}</span></li>; })}</ol> : <p className="empty">시간을 쓴 미정답 문항이 없습니다.</p>}</section></div>
    <section className="panel"><div className="section-heading"><h2>문항 특성별 결과</h2><label>분석 기준 <select value={by} onChange={e => setBy(e.target.value as typeof by)}><option value="language">언어</option><option value="stimulusType">자극 유형</option><option value="contextNovelty">맥락</option></select></label></div><div className="table-scroll"><table><thead><tr><th>분류</th><th>시도/전체</th><th>정확도</th><th>중앙 시간</th></tr></thead><tbody>{groups.map(g => <tr key={g.label}><td>{g.label}</td><td>{g.attempted}/{g.total}</td><td>{g.attempted ? percent(g.accuracy) : '—'}</td><td>{g.attempted ? timeText(g.medianMs) : '—'}</td></tr>)}</tbody></table></div><p className="panel-note">기존 문항에서 없는 메타데이터는 ‘미지정’입니다. 작은 표본의 차이를 일반화하지 마세요.</p></section>
    <section className="panel" id="exam-review"><div className="section-heading"><h2>시험 후 문항 검토</h2><span className="small muted">진단·확신도 입력은 선택 사항</span></div><div className="exam-review-list">{rows.map((r, i) => <button className={`button ${r.questionId === reviewId ? 'primary' : 'secondary'}`} aria-pressed={r.questionId === reviewId} onClick={() => setReviewId(r.questionId)} key={r.id}>{i + 1}번 · {r.correct === true ? '정답' : r.correct === false ? '오답' : '미응답'}</button>)}</div>
      {review && reviewQuestion && <article className="exam-review-detail"><p className="small muted">{TAXONOMY[reviewQuestion.domain]} / {reviewQuestion.subdomain} · {reviewQuestion.sourceType}{reviewQuestion.fixture ? ' · 개발용' : ''}</p><h3 className="question-text">{reviewQuestion.question}</h3><p>내 답: {review.selectedAnswer === null ? '미응답' : `${review.selectedAnswer + 1}. ${reviewQuestion.choices[review.selectedAnswer]}`}</p><p><strong>정답: {reviewQuestion.answer + 1}. {reviewQuestion.choices[reviewQuestion.answer]}</strong></p><p className="question-text">{reviewQuestion.explanation}</p><p>문항 시간 {timeText(review.responseTimeMs)} · 재방문 {Math.max(0, review.visitCount - 1)}회 · 답안 변경 {review.answerChangeCount ?? 0}회</p><p>첫 판단 {review.firstDecision ?? '없음'} → 최종 판단 {review.decisions.at(-1)?.decision ?? '없음'}</p><div className="tags">{examFlags(data, session, review).map(f => <span className="badge warning" key={f}>{f}</span>)}</div><Reflection data={data} session={session} response={review} onSave={onSave} busy={busy}/></article>}
    </section>
    <details className="method-note"><summary>진단과 시간 계산 기준</summary><p>EASY_MISS: 난이도 1–2 오답. LONG_WRONG: 오답이며 문항 시간이 목표의 1.5배 초과. BAD_INVESTMENT: 미정답(오답·미응답)이며 문항 시간이 목표의 2배 초과.</p><p>KNOWN_BUT_LOST: 시간 만료로 종료된 시험의 미응답 문항 중 난이도 1–2이거나, 시험 시작 전에 완료한 Training에서 같은 문항의 마지막 제출 답안이 정답인 경우입니다. 직접 제출·다른 문항/주제 성적·이전 REAL EXAM은 근거로 쓰지 않습니다.</p><p>문항 시간은 첫 표시부터 이동까지와 모든 재방문 시간을 합산합니다. 선택 후에도 이동 전까지 계속 누적하며, 마감 시각에서 멈춥니다. 중앙값은 답안을 남긴 문항만 포함합니다. 초 단위로 반올림한 실용적 기록이며 실제 주의 집중 시간을 측정하지 않습니다. 진단은 과학적으로 검증된 심리측정이 아닙니다.</p></details>
  </>;
}

function Reflection({ data, session, response: r, onSave, busy }: { data: StudyData; session: Session; response: Response; onSave: Save; busy: boolean }) {
  async function save(confidence: Response['confidence'], failureType: FailureType | null) { await onSave(reflectExam(data, session.id, r.questionId, confidence, failureType)); }
  return <div className="exam-reflection"><label>확신도 (선택)<select aria-label="시험 후 확신도" disabled={busy} value={r.confidence ?? ''} onChange={e => void save(e.target.value ? Number(e.target.value) as Response['confidence'] : null, r.failureType)}><option value="">미기록</option>{[1, 2, 3, 4, 5].map(c => <option key={c} value={c}>{c}</option>)}</select></label>{r.correct !== true && <label>실패 유형 (선택)<select aria-label="시험 후 실패 유형" disabled={busy} value={r.failureType ?? ''} onChange={e => void save(r.confidence, e.target.value ? e.target.value as FailureType : null)}><option value="">미기록</option>{Object.entries(FAILURES).map(([code, label]) => <option key={code} value={code}>{code} · {label}</option>)}</select></label>}</div>;
}
